development:
    adapter: sqlserver
    host: '192.168.20.18'
   # database: 'superiorweb'
    database: 'swtest'
    username: 'fbowers'
    password: '3769'



production:
    adapter: sqlserver
    host: '192.168.20.18'
    database: 'superiorweb'
   # database: 'swtest'
    username: 'fbowers'
    password: '3769'
